[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = './test/'
remappings = [
  '@openzeppelin/=node_modules/@openzeppelin/',
  '@thirdweb-dev/=node_modules/@thirdweb-dev/',
  'hardhat/=node_modules/hardhat/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config